#!/usr/bin/env python3
"""Add visible stack indicators: colored Obsidian banners in each SKILL.md
+ a CSS snippet that colors the tags.

Three pieces installed:

1. Per-skill banners: a colored callout block at the top of each SKILL.md
   indicating which stack(s) it belongs to. Rendered as colored banners by
   Obsidian.

2. CSS snippet at <vault>/.obsidian/snippets/forge-stack-colors.css that
   colors #engineering (blue), #data (green), #operations (amber) in the
   tag pane AND inline. Also colors #rejected/#archived/#installed/#gate-failed.

3. Updates to stacks.py: `inject_stack_banners(skill_path, stacks)` helper +
   set_skill_stacks() integration. Adds a `forge stack sync-visuals` command
   that re-applies banners + tags from frontmatter (in case of drift).

Banners look like:
    > [!engineering] Engineering Stack
    > This skill is part of the engineering team's curated subset.

Obsidian renders [!engineering] as a blue callout because the CSS snippet
maps `.callout[data-callout="engineering"]` to the engineering color.

Run from inside ~/code/skill-forge:
    python3 add-stack-banners.py
"""
import ast
import re
import sys
from pathlib import Path


# Stack → (display name, hex color). The CSS snippet uses these.
STACK_COLORS = {
    "engineering": ("Engineering", "#3b82f6"),  # blue
    "data": ("Data", "#10b981"),                # green
    "operations": ("Operations", "#f59e0b"),    # amber
}


CSS_SNIPPET = """/* forge-stack-colors.css
 * Generated by skill-forge — colors stack tags + callout banners.
 * Auto-loaded if enabled in Obsidian: Settings → Appearance → CSS snippets.
 */

/* ---------- Stack tags in tag pane and inline ---------- */

.tag[href="#engineering"],
a.tag[href="#engineering"],
.cm-hashtag[data-tag="engineering"],
.cm-hashtag-end:has(+ .cm-hashtag[data-tag="engineering"]) {
  background-color: #3b82f6 !important;
  color: white !important;
  border-color: #2563eb !important;
}

.tag[href="#data"],
a.tag[href="#data"],
.cm-hashtag[data-tag="data"] {
  background-color: #10b981 !important;
  color: white !important;
  border-color: #059669 !important;
}

.tag[href="#operations"],
a.tag[href="#operations"],
.cm-hashtag[data-tag="operations"] {
  background-color: #f59e0b !important;
  color: white !important;
  border-color: #d97706 !important;
}

/* ---------- Stack banners (callout blocks) ---------- */

.callout[data-callout="engineering"] {
  --callout-color: 59, 130, 246;
  --callout-icon: lucide-wrench;
}
.callout[data-callout="data"] {
  --callout-color: 16, 185, 129;
  --callout-icon: lucide-database;
}
.callout[data-callout="operations"] {
  --callout-color: 245, 158, 11;
  --callout-icon: lucide-factory;
}

/* ---------- Lifecycle tags ---------- */

.tag[href="#archived"], a.tag[href="#archived"], .cm-hashtag[data-tag="archived"] {
  background-color: #6b7280 !important;
  color: white !important;
}
.tag[href="#installed"], a.tag[href="#installed"], .cm-hashtag[data-tag="installed"] {
  background-color: #10b981 !important;
  color: white !important;
}
.tag[href="#rejected"], a.tag[href="#rejected"], .cm-hashtag[data-tag="rejected"] {
  background-color: #ef4444 !important;
  color: white !important;
}
.tag[href="#gate-failed"], a.tag[href="#gate-failed"], .cm-hashtag[data-tag="gate-failed"] {
  background-color: #f87171 !important;
  color: white !important;
}
"""


# The helper function injected into stacks.py to manage banners.
BANNERS_HELPER = '''

# ---------- Inline Obsidian banners -----------------------------------------

# Display info per stack. Keep in sync with the CSS snippet.
_STACK_DISPLAY = {
    "engineering": "Engineering",
    "data": "Data",
    "operations": "Operations",
}


_BANNER_BLOCK_RE = re.compile(
    r"^<!-- forge-stack-banners -->\\n(?:>.*\\n|\\n)+",
    re.MULTILINE,
)

_TAGS_BLOCK_RE = re.compile(
    r"^<!-- forge-stack-tags -->\\n[^\\n]*\\n+",
    re.MULTILINE,
)


def inject_stack_banners(skill_path: Path, stacks: list[str]) -> bool:
    """Sync BOTH the colored banner block AND the inline tag line at the top
    of a SKILL.md so they stay in sync.

    Strategy: strip any existing forge-managed marker blocks (banners + tags)
    from the start of the body, then rebuild them fresh in canonical order:

        ---frontmatter---

        <!-- forge-stack-banners -->
        > [!stack1] ...
        > ...

        > [!stack2] ...
        > ...

        <!-- forge-stack-tags -->
        #stack1 #stack2

        # Body...

    If `stacks` is empty, both blocks are removed.

    Returns True if the file changed.

    Note: this function takes ownership of the tags block too, so it's safe
    to call this OR inject_stack_tags but not both back-to-back from the
    same caller. set_skill_stacks calls this one only.
    """
    try:
        text = skill_path.read_text(encoding="utf-8")
    except OSError:
        return False

    m = re.match(r"^(---[ \\t]*\\n.*?\\n---[ \\t]*\\n)", text, re.DOTALL)
    if not m:
        return False
    fm_end = m.end()
    before = text[:fm_end]
    after = text[fm_end:]

    # Strip any leading blank lines, then any existing marker blocks (banners,
    # tags, in either order). Loop until nothing strips, so out-of-order or
    # duplicate markers all get cleaned up.
    cleaned = after.lstrip("\\n")
    while True:
        prev = cleaned
        cleaned = _BANNER_BLOCK_RE.sub("", cleaned, count=1)
        cleaned = _TAGS_BLOCK_RE.sub("", cleaned, count=1)
        cleaned = cleaned.lstrip("\\n")
        if cleaned == prev:
            break

    # Build desired blocks
    blocks = []
    if stacks:
        callout_blocks = []
        for stack in stacks:
            display = _STACK_DISPLAY.get(stack, stack.capitalize())
            callout_blocks.append(
                f"> [!{stack}] {display} Stack\\n"
                f"> This skill is part of the {display.lower()} team\\'s curated subset."
            )
        banners_block = (
            "<!-- forge-stack-banners -->\\n"
            + "\\n\\n".join(callout_blocks)
        )
        tags = " ".join(f"#{s.strip()}" for s in stacks if s.strip())
        tags_block = f"<!-- forge-stack-tags -->\\n{tags}"
        blocks.append(banners_block)
        blocks.append(tags_block)

    if blocks:
        # Separate frontmatter from blocks by one blank line, blocks from each
        # other by one blank line, blocks from body by one blank line.
        managed_section = "\\n" + "\\n\\n".join(blocks) + "\\n\\n"
    else:
        managed_section = ""

    new_after = managed_section + cleaned
    new_text = before + new_after
    if new_text == text:
        return False
    skill_path.write_text(new_text, encoding="utf-8")
    return True
'''


# A small change to set_skill_stacks: also call inject_stack_banners.
SET_FN_NEW_TAIL = '''    # Sync the inline banners + #stack tags. inject_stack_banners is the
    # single source of truth for both visual elements at the top of the file.
    visuals_changed = inject_stack_banners(skill_md_path, stacks)

    return frontmatter_changed or visuals_changed
'''


# Add `sync-visuals` subcommand to cmd_stack
SYNC_VISUALS_BLOCK = '''
    if sub == "sync-visuals":
        from .stacks import list_skill_assignments, inject_stack_banners
        assignments = list_skill_assignments(config)
        changed = 0
        for skill_md, stacks in assignments.items():
            if stacks == ["(never_publish)"]:
                stacks = []
            if inject_stack_banners(skill_md, stacks):
                changed += 1
                print(f"  + {skill_md.parent.name}: {stacks or '(removed)'}")
        print(f"\\nsynced {changed} skill(s)")
        return 0
'''


def main() -> int:
    forge_dir = Path("forge")
    if not (forge_dir / "stacks.py").exists():
        print("X forge/stacks.py not found — run install-stacks.py first")
        return 1

    # ---- Step 1: add inject_stack_banners to stacks.py ----
    stacks_path = forge_dir / "stacks.py"
    s = stacks_path.read_text()

    if "def inject_stack_banners" in s:
        print("  + inject_stack_banners already in stacks.py")
    else:
        s = s.rstrip() + "\n" + BANNERS_HELPER
        print("  + added inject_stack_banners() to stacks.py")

    # ---- Step 2: update set_skill_stacks to call inject_stack_banners ----
    # Find the existing tail (which calls only inject_stack_tags) and replace it.
    old_tail = '''    # Now sync the inline #stack tags. inject_stack_tags handles add/update/remove.
    tags_changed = inject_stack_tags(skill_md_path, stacks)

    return frontmatter_changed or tags_changed'''

    if "visuals_changed" in s:
        print("  + set_skill_stacks already wired to banners")
    elif old_tail in s:
        s = s.replace(old_tail, SET_FN_NEW_TAIL.rstrip(), 1)
        print("  + wired set_skill_stacks to also call inject_stack_banners")
    else:
        print("  ! set_skill_stacks tail didn't match expected shape")
        print("    Banners will work via sync-visuals but won't auto-sync on assign.")
        print("    (you can manually run `forge stack sync-visuals` after assign)")

    stacks_path.write_text(s)

    # ---- Step 3: add sync-visuals subcommand to commands.py ----
    cmds_path = forge_dir / "commands.py"
    cmds = cmds_path.read_text()

    if "sync-visuals" in cmds:
        print("  + sync-visuals branch already in cmd_stack")
    else:
        anchor = '    print(f"unknown stack subcommand: {sub}")'
        if anchor not in cmds:
            print("X couldn't find cmd_stack dispatcher tail")
            return 1
        cmds = cmds.replace(anchor, SYNC_VISUALS_BLOCK + "\n" + anchor, 1)
        cmds_path.write_text(cmds)
        print("  + added sync-visuals branch to cmd_stack")

    # ---- Step 4: add the subparser ----
    main_path = forge_dir / "__main__.py"
    main_src = main_path.read_text()
    if 'stack_sub.add_parser("sync-visuals"' not in main_src:
        # Insert after sync-tags subparser if it exists, else after assign
        anchor_options = [
            'stack_sub.add_parser("sync-tags", help="Regenerate inline #stack tags from frontmatter")',
            'stack_sub.add_parser("assign", help="Interactive: assign existing skills to stacks")',
        ]
        for anchor in anchor_options:
            if anchor in main_src:
                insertion = anchor + '\n    stack_sub.add_parser("sync-visuals", help="Regenerate stack tags AND banners from frontmatter")'
                main_src = main_src.replace(anchor, insertion, 1)
                main_path.write_text(main_src)
                print("  + added sync-visuals subparser to __main__.py")
                break
        else:
            print("  ! no suitable anchor for sync-visuals subparser; add manually")
    else:
        print("  + sync-visuals subparser already wired")

    # ---- Parse-check ----
    try:
        ast.parse(stacks_path.read_text())
        ast.parse(cmds_path.read_text())
        ast.parse(main_path.read_text())
        print("  + all files parse cleanly")
    except SyntaxError as e:
        print(f"X syntax error after patch: {e}")
        return 1

    # Clear .pyc
    pycache = Path("forge/__pycache__")
    if pycache.exists():
        for pyc in pycache.glob("*.pyc"):
            pyc.unlink()

    # ---- Step 5: install the CSS snippet into the vault ----
    print()
    print("Installing Obsidian CSS snippet...")
    env_vars = {}
    env_file = Path(".env")
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, v = line.split("=", 1)
                env_vars[k.strip()] = v.strip()

    vault_path = env_vars.get("VAULT_PATH")
    if not vault_path:
        print("  X VAULT_PATH not in .env — skipping CSS install")
    else:
        vault = Path(vault_path).expanduser()
        snippets_dir = vault / ".obsidian" / "snippets"
        snippets_dir.mkdir(parents=True, exist_ok=True)
        css_path = snippets_dir / "forge-stack-colors.css"
        css_path.write_text(CSS_SNIPPET, encoding="utf-8")
        print(f"  + wrote {css_path}")
        print()
        print("  ENABLE THE SNIPPET IN OBSIDIAN:")
        print("    Settings → Appearance → CSS snippets → enable 'forge-stack-colors'")
        print("    (Reload Obsidian with Cmd+R first if you don't see it listed)")

    # ---- Step 6: backfill all skills with banners ----
    print()
    print("Backfilling banners on existing skills...")
    import subprocess
    result = subprocess.run(
        ["python3", "-m", "forge", "stack", "sync-visuals"],
        capture_output=True, text=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"X sync-visuals failed: {result.stderr}")
        return 1

    print()
    print("+ done")
    print()
    print("Each SKILL.md now starts with colored callout banner(s) showing its stack(s).")
    print("Tag pane will show colored #engineering / #data / #operations chips once you")
    print("enable the CSS snippet in Obsidian.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
