"""skill-forge command-line interface."""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

from .config import load_config, Config
from .capture import read_captures, write_captures
from .sources import read_all
from .cluster import cluster_captures, write_clusters, read_clusters
from .drafter import draft_skill, proposal_path, extract_skill_name, wrap_proposal
from .watch import watch_loop, process_approved_file


def cmd_init(args, config: Config) -> int:
    """Create vault folders and skills repo skeleton."""
    for d in [
        config.inbox_dir,
        config.proposals_dir,
        config.approved_dir,
        config.archive_dir,
        config.state_dir,
        config.skills_repo_path,
    ]:
        d.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {d}")

    readme = config.vault_path / "README.md"
    if not readme.exists():
        readme.write_text(
            "# skill-forge vault\n\n"
            "- `inbox/` — drop notes about tasks you want skills for\n"
            "- `proposals/` — AI-drafted SKILL.md awaiting your review\n"
            "- `approved/` — drag a proposal here to ship it\n"
            "- `archive/` — rejected or already-installed proposals\n",
            encoding="utf-8",
        )
        print(f"  ✓ {readme}")

    repo_readme = config.skills_repo_path / "README.md"
    if not repo_readme.exists():
        repo_readme.write_text(
            "# claude-skills\n\nAuto-generated by skill-forge. Each subfolder is one skill.\n",
            encoding="utf-8",
        )
        print(f"  ✓ {repo_readme}")

    print("\nDone. Next: drop a note in inbox/ or set up Claude Code log scanning, then run `forge run`.")
    return 0


def cmd_scan(args, config: Config) -> int:
    captures = read_all(config)
    written = write_captures(captures, config.captures_path)
    total = len(read_captures(config.captures_path))
    print(f"scanned {len(captures)} captures, {written} new (total stored: {total})")
    return 0


def cmd_cluster(args, config: Config) -> int:
    captures = read_captures(config.captures_path)
    if not captures:
        print("no captures yet — run `forge scan` first")
        return 1
    clusters = cluster_captures(
        captures,
        min_size=config.cluster_min_size,
        threshold=config.cluster_similarity_threshold,
    )
    write_clusters(clusters, config.clusters_path)
    print(f"clustered {len(captures)} captures into {len(clusters)} cluster(s):")
    for c in clusters:
        print(f"  {c.id}  ({c.size()} members)  {c.representative_goal[:60]}")
    return 0


def _load_drafted(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _save_drafted(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def cmd_draft(args, config: Config) -> int:
    clusters = read_clusters(config.clusters_path)
    if not clusters:
        print("no clusters — run `forge cluster` first")
        return 1

    captures_by_id = {c.id: c for c in read_captures(config.captures_path)}
    drafted = _load_drafted(config.drafted_path)

    if args.cluster_id:
        targets = [c for c in clusters if c.id == args.cluster_id]
        if not targets:
            print(f"no cluster with id {args.cluster_id}")
            return 1
    else:
        targets = [c for c in clusters if c.fingerprint not in drafted]
        if not targets:
            print("nothing new to draft")
            return 0

    config.proposals_dir.mkdir(parents=True, exist_ok=True)

    for cluster in targets:
        members = [captures_by_id[mid] for mid in cluster.member_ids if mid in captures_by_id]
        if not members:
            continue
        print(f"drafting {cluster.id} ({len(members)} members)...")
        try:
            skill_md = draft_skill(config, cluster, members)
        except Exception as e:
            print(f"  ✗ draft failed: {e}")
            continue
        name = extract_skill_name(skill_md)
        out_path = proposal_path(config, cluster, name)
        wrapped = wrap_proposal(skill_md, cluster, len(members))
        out_path.write_text(wrapped, encoding="utf-8")
        print(f"  ✓ {out_path}")
        drafted[cluster.fingerprint] = {
            "cluster_id": cluster.id,
            "proposal_path": str(out_path),
            "skill_name": name,
        }

    _save_drafted(config.drafted_path, drafted)
    return 0


def cmd_run(args, config: Config) -> int:
    print("→ scan")
    if cmd_scan(args, config) != 0:
        return 1
    print("→ cluster")
    if cmd_cluster(args, config) != 0:
        return 1
    print("→ draft")
    return cmd_draft(args, config)


def cmd_watch(args, config: Config) -> int:
    watch_loop(config)
    return 0


def cmd_status(args, config: Config) -> int:
    captures = read_captures(config.captures_path)
    clusters = read_clusters(config.clusters_path)
    drafted = _load_drafted(config.drafted_path)
    proposals = list(config.proposals_dir.glob("*.md")) if config.proposals_dir.exists() else []
    approved = list(config.approved_dir.glob("*.md")) if config.approved_dir.exists() else []
    archive = list(config.archive_dir.glob("*.md")) if config.archive_dir.exists() else []

    print("skill-forge status")
    print(f"  captures stored:  {len(captures)}")
    print(f"  clusters:         {len(clusters)}")
    print(f"  drafted:          {len(drafted)}")
    print(f"  proposals/:       {len(proposals)} awaiting review")
    print(f"  approved/:        {len(approved)} pending sync")
    print(f"  archive/:         {len(archive)}")
    print(f"  skills repo:      {config.skills_repo_path}")
    return 0


def cmd_install_cron(args, config: Config) -> int:
    import subprocess
    forge_bin = Path(sys.argv[0]).resolve()
    line = f"0 2 * * * cd {Path.cwd()} && {sys.executable} -m forge run >> ~/.skill-forge/cron.log 2>&1"
    print("Add this line to your crontab (run `crontab -e`):")
    print()
    print(f"    {line}")
    print()
    print("It runs `forge run` nightly at 02:00 local time.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="forge", description="Self-updating Claude skill builder")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init", help="Set up vault + skills repo folders").set_defaults(fn=cmd_init)
    sub.add_parser("scan", help="Pull captures from configured sources").set_defaults(fn=cmd_scan)
    sub.add_parser("cluster", help="Cluster captures into skill candidates").set_defaults(fn=cmd_cluster)

    draft_p = sub.add_parser("draft", help="Draft SKILL.md for new clusters")
    draft_p.add_argument("cluster_id", nargs="?", help="Specific cluster id (default: all new)")
    draft_p.set_defaults(fn=cmd_draft)

    sub.add_parser("run", help="scan → cluster → draft (cron target)").set_defaults(fn=cmd_run)
    sub.add_parser("watch", help="Daemon: sync approved/ to git").set_defaults(fn=cmd_watch)
    sub.add_parser("status", help="Show pipeline state").set_defaults(fn=cmd_status)
    sub.add_parser("install-cron", help="Print crontab line to install").set_defaults(fn=cmd_install_cron)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        config = load_config()
    except RuntimeError as e:
        print(f"config error: {e}", file=sys.stderr)
        print("Tip: copy .env.example to .env and fill it in.", file=sys.stderr)
        return 2
    return args.fn(args, config)


if __name__ == "__main__":
    sys.exit(main())
